### ISSUE TITLE
"Missing deck name" every time

### ISSUE THREAD

**Issue by asakura42** [ap4y/leaf#3]
`[date] [time] Missing deck name`
Tried all commands from readme but nothing.
It's just CLI version, not server part.

**Comment by ap4y** [comment]
`leaf` CLI expects you to provide command and a deck name. For example to start review for the sample hiragana deck from the repo you have to run this command:

```bash
go run ./cmd/leaf -decks ./fixtures review Hiragana
```

I have added list of currently supported commands and additional information to the readme in [this commit](https://github.com/ap4y/leaf/commit/b457eb75728ede0409415550decc448d07d1c961). I have also updated CLI to return additional [information](https://github.com/ap4y/leaf/commit/5c8222d3cf1e76a9035d58834005bdec50bef494) when `-h` argument is supplied.
